
// DB users rights constants
const UR_EDITRULES         = 'ur001';
const UR_EDITVARS          = 'ur002';
const UR_EDITCONTENT       = 'ur003';
const UR_DELOLDRECORDS     = 'ur004';
const UR_EDITCOSTS         = 'ur005';
const UR_VIPWORK           = 'ur006';
const UR_EDITCOMPRULES     = 'ur007';
const UR_EDITCOMPVARS      = 'ur008';


// used only in operator's program
const UR_X_REBOOTSHUTDOWN  = 'ur030';
const UR_X_LOGOFF          = 'ur031';
const UR_X_TURNSHELL       = 'ur032';
const UR_X_TURNAUTOLOGON   = 'ur033';
const UR_X_TURNMONITOR     = 'ur034';
const UR_X_TURNBLOCK       = 'ur035';
const UR_X_EXECUTE         = 'ur036';
const UR_X_COPYDELFILES    = 'ur037';
const UR_X_KILLTASKS       = 'ur038';
const UR_X_CLEARSTAT       = 'ur039';
const UR_X_RESTOREVMODE    = 'ur040';
const UR_X_SENDMESSAGE     = 'ur041';
const UR_X_TIMESYNC        = 'ur042';
const UR_X_MACHINESINFO    = 'ur043';
const UR_X_CLIENTUPDATE    = 'ur044';
const UR_X_RSRD            = 'ur045';
const UR_X_RFM             = 'ur046';
const UR_X_ROLLBACK        = 'ur047';
const UR_X_CLIENTUNINSTALL = 'ur048';

