
// same list is in ..\fid.inc !!!

const FID_REBOOT               = 1001;
const FID_SHUTDOWN             = 1002;
const FID_LOGOFF               = 1003;
const FID_KILLALL              = 1004;
const FID_SENDMESSAGE          = 1005;
const FID_TURNMONITORON        = 1006;
const FID_TURNMONITOROFF       = 1007;
const FID_UNBLOCK              = 1008;
const FID_BLOCK                = 1009;
const FID_RESTOREVMODE         = 1010;
const FID_SOMEINFOCOMP         = 1011;
const FID_EXECSTAT             = 1012;
const FID_SCREEN               = 1013;
const FID_WEBCAM               = 1014;
const FID_SCREENCONTROL        = 1015;
const FID_WEBCAMCONTROL        = 1016;
const FID_TURNSHELLON          = 1017;
const FID_TURNSHELLOFF         = 1018;
const FID_TURNCURRENTSHELLOFF  = 1019;
const FID_TURNAUTOLOGONON      = 1020;
const FID_TURNAUTOLOGONOFF     = 1021;
const FID_TIMESYNC             = 1022;
const FID_CLEAREXECSTAT        = 1023;
const FID_EXECUTECMDLINE       = 1024;
const FID_EXECUTEREG           = 1025;
const FID_EXECUTEBAT           = 1026;
const FID_COPYFILES            = 1027;
const FID_DELETEFILES          = 1028;
const FID_RFM                  = 1029;
const FID_RD                   = 1030;
const FID_CLIENTUPDATE         = 1031;
const FID_HIBERNATE            = 1032;
const FID_SUSPEND              = 1033;
const FID_RLBINFO              = 1034;
const FID_RLBSAVE1             = 1035;
const FID_RLBSAVE2             = 1036;
const FID_RLBHELP              = 1037;
const FID_SOMEINFOUSER         = 1038;
const FID_CLIENTUNINSTALL      = 1039;
const FID_TEMPTURNSHELLOFF     = 1040;

